kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myoperator
subjects:
- kind: ServiceAccount
  name: myoperator
roleRef:
  kind: Role
  name: myoperator
  apiGroup: rbac.authorization.k8s.io
